name: Discord Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Detailed Webhook
        uses: sarisia/actions-status-discord@v1
        with:
          username: "The Face Collector Bot" # O el nombre que prefieras
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: 0x5865F2